### ISSUE TITLE
Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by cpavlatos** [say8425/aws-secrets-manager-actions#123]
I am getting this warning:

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: say8425/aws-secrets-manager-actions.

**Comment by say8425** [comment]
Thanks for reporting!

I'm already working on [Version 3](https://github.com/say8425/aws-secrets-manager-actions/tree/version-3) including upgrading node.js 16 
But this issue looks important, so I will upgrade node.js 16 on first.
