### ISSUE TITLE
Still seeing references to node 12 in latest release

### ISSUE THREAD

**Issue by russ-marcie** [say8425/aws-secrets-manager-actions#129]
The latest release (v2.2.0) claims a move to node16, however I'm see seeing references to node 12: 
https://github.com/say8425/aws-secrets-manager-actions/blob/v2.2.0/action.yml#L23 

Also receiving warnings from pipeline runs:
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: say8425/aws-secrets-manager-actions@v2.2.0.

**Comment by say8425** [comment]
Thank you for issue up! Now on we use node.js version 16. Thank you.
