### ISSUE TITLE
Support for plaintext values

### ISSUE THREAD

**Issue by andrew-1L** [say8425/aws-secrets-manager-actions#24]
Very nice work! One issue I ran into when testing this myself is that AWS SM supports raw text values, in addition to key-value pairs. It would be good to have a flag to set whether to try to parse key value pairs, or just read the raw secretstring and assign it to a supplied environment variable name.

I don't know how often plaintext gets used in SM overall, but some other tools expect plaintext values such as https://github.com/Accenture/hiera-aws-sm, so it would be great to support that as an option.

**Comment by say8425** [comment]
I'm sorry to late reply your issue.
That is interesting. I did not think plain text can be get used in AWS SM.
I'll try to add a flag for key/value for raw secret string.
And thank you to feedback.

**Comment by monkeymon** [comment]
Interestingly, I'm working on on AWS SM to keep encrypted SSH private for my CI user. 
Creating a PR for this.

**Comment by say8425** [comment]
Plaintext values feature was released on 1.2.0 version.
Thank you for your contributing @andrew-1L, @monkeymon 

Have a great coding 👩‍💻👨‍💻
