### ISSUE TITLE
set-env issue on v1.2.1

### ISSUE THREAD

**Issue by tatchiuleung** [say8425/aws-secrets-manager-actions#45]
Thank you for the GH action! We have recently hit the `set-env` issue.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

I see that the most release `v1.3.0` is not out yet:
https://github.com/say8425/aws-secrets-manager-actions/runs/1338353950?check_suite_focus=true

Would you please let us know if there is a way to access a working version?

**Comment by say8425** [comment]
@tatchiuleung Thank you for your issue.

In this time, No.

But I'll fix it and release `v1.3.1` in this week.

**Comment by say8425** [comment]
@tatchiuleung Thanks for waiting.
I released [v1.3.2](https://github.com/say8425/aws-secrets-manager-actions/releases/tag/v1.3.2) fixing a [set-env issue](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).

You can read code changes at https://github.com/say8425/aws-secrets-manager-actions/pull/41.
