### ISSUE TITLE
Fatal bug in v1.3.2

### ISSUE THREAD

**Issue by abronin** [say8425/aws-secrets-manager-actions#48]
Action just crashes with this error:
`File not found: '/home/runner/work/_actions/say8425/aws-secrets-manager-actions/v1.3.2/dist/index.js'`

**Comment by say8425** [comment]
I'm sorry for your issue.
I'll fix it until that time use v1.2.1, that will be work.

```
- name: aws-secrets-manager-actions
   uses: say8425/aws-secrets-manager-actions@v1.2.1
```

**Comment by abronin** [comment]
Yes, I'm using v1.2.1. Thank you!

**Comment by say8425** [comment]
I rollbacked the v1 from v1.3.2 to v1.2.1.
`say8425/aws-secrets-manager-actions@v1` will be fine.
