### ISSUE TITLE
Erroring from deprecated set-env command

### ISSUE THREAD

**Issue by aroder** [say8425/aws-secrets-manager-actions#57]
Hi, when I try to use your action, I get errors with messages like "The `set-env` command is disabled. "

I believe this is because your most recent release is v1.2.1, which was released before you upgraded to @actions/core version 1.2.6.

Would you mind publishing a new release to the actions marketplace?

**Comment by say8425** [comment]
```
- name: aws-secrets-manager-actions
  uses: say8425/aws-secrets-manager-actions@v2
```

@aroder Finally I release v2.0.0. Please use v2. It will fix set-env issue. Thanks.
