### ISSUE TITLE
Mask env variables

### ISSUE THREAD

**Issue by brunocascio** [say8425/aws-secrets-manager-actions#8]
Hey @say8425,

Thanks a lot for your open source contribution!

I'm wondering if is there a way to mask the environment variables because they're shown in plain text. I found this https://github.community/t5/GitHub-Actions/GitHub-Actions-Mask-non-GitHub-Env-Secrets/td-p/29714

Thanks in advance!

**Comment by say8425** [comment]
Wow! Thank you for your kindness!!
I knew these environment values should be masked, but I forgot to mask it.
I'll fix it right now.
And your issue is first contributing and very IMPORTANT security issue for this open source.
So I thanks a lot your contributing.
I wish you have a great coding day.

**Comment by brunocascio** [comment]
You're welcome, we are the open-source community :dancer: and we are humans so we can make mistakes. Don't worry about it :+1: 

Have a nice day! 

PD: Actions logs are deleted after a couple of days. I've just posted a request to clear logs in a manually way. https://github.community/t5/GitHub-Actions/Ability-to-clear-action-logs-manually/m-p/39108#
